CREATE TABLE [dbo].[fReceipts] (
    [receipt_id]                 NVARCHAR (255)   NOT NULL,
    [terminalid]                 NVARCHAR (255)   NULL,
    [warehouseid]                NVARCHAR (255)   NULL,
    [users_id]                   NVARCHAR (255)   NULL,
    [dates]                      DATETIME         NULL,
    [marker]                     NVARCHAR (255)   NULL,
    [corp_code]                  NVARCHAR (255)   NULL,
    [fr_session]                 NVARCHAR (255)   NULL,
    [doc_type]                   NVARCHAR (255)   NULL,
    [doc_num]                    NVARCHAR (255)   NULL,
    [doc_num_session]            NVARCHAR (255)   NULL,
    [discount]                   DECIMAL (20, 10) NULL,
    [discount_misc]              DECIMAL (20, 10) NULL,
    [amount]                     DECIMAL (20, 10) NULL,
    [round_amount]               DECIMAL (20, 10) NULL,
    [pay_cash]                   DECIMAL (20, 10) NULL,
    [pay_card]                   DECIMAL (20, 10) NULL,
    [pay_tare]                   DECIMAL (20, 10) NULL,
    [pay_credit]                 DECIMAL (20, 10) NULL,
    [pay_bonus_id]               NVARCHAR (255)   NULL,
    [pay_bonus_amount]           DECIMAL (20, 10) NULL,
    [pinpad_name]                NVARCHAR (255)   NULL,
    [terminal_number]            NVARCHAR (255)   NULL,
    [short_fiscal_serial_number] NVARCHAR (255)   NULL,
    [device_model_name]          NVARCHAR (255)   NULL,
    [device_model_version]       NVARCHAR (255)   NULL,
    [terminal_description]       NVARCHAR (255)   NULL,
    [is_electronic]              NVARCHAR (255)   NULL,
    [fiscal_attribute]           NVARCHAR (255)   NULL,
    [vat10_sum]                  DECIMAL (20, 10) NULL,
    [vat18_sum]                  DECIMAL (20, 10) NULL,
    [vat20_sum]                  DECIMAL (20, 10) NULL,
    [items_count]                INT              NULL
);

